### PR TITLE
macOS build fix

### PR DESCRIPTION
**Pull request by farhangnaderi**
This is initial sketch. Let me know if I am missing anything here!

### CODE REVIEW

File: COMPILE.md [hunk 1]
```diff
@@ -118,7 +118,7 @@ export LDFLAGS="$QT_HOME/lib"
 Clone the repository into **~/plotjuggler_ws**:
 
 ```shell
-git clone https://github.com/facontidavide/PlotJuggler.git ~/plotjuggler_ws/src/PlotJuggler
+git clone https://github.com/PX4/PlotJuggler.git ~/plotjuggler_ws/src/PlotJuggler
```
Comment (mrpollo) [inline COMPILE.md]: I don't think there's a need to change this, we want to submit a PR back to them eventually

**Comment by mrpollo** [comment]
My issue still needs to be solved. Has anyone figured this one out? I'm on apple silicon.

cc @MaEtUgR 

```
 cmake -S src/PlotJuggler -B build/PlotJuggler -DCMAKE_INSTALL_PREFIX=install 
-- The C compiler identification is AppleClang 15.0.0.15000309
-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - broken
CMake Error at /opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/Users/rroche/Work/Dronecode/PlotJuggler/plotjuggler_ws/build/PlotJuggler/CMakeFiles/CMakeScratch/TryCompile-8kItw2'

    Run Build Command(s): /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_b372c/fast
    /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_b372c.dir/build.make CMakeFiles/cmTC_b372c.dir/build
    Building C object CMakeFiles/cmTC_b372c.dir/testCCompiler.c.o
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -MD -MT CMakeFiles/cmTC_b372c.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_b372c.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_b372c.dir/testCCompiler.c.o -c /Users/rroche/Work/Dronecode/PlotJuggler/plotjuggler_ws/build/PlotJuggler/CMakeFiles/CMakeScratch/TryCompile-8kItw2/testCCompiler.c
    Linking C executable cmTC_b372c
    /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b372c.dir/link.txt --verbose=1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names /opt/homebrew/opt/qt@5/lib  CMakeFiles/cmTC_b372c.dir/testCCompiler.c.o -o cmTC_b372c
    ld: file cannot be mmap()ed, errno=22 path=/opt/homebrew/opt/qt@5/lib in '/opt/homebrew/opt/qt@5/lib'
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_b372c] Error 1
    make: *** [cmTC_b372c/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)


-- Configuring incomplete, errors occurred!
```

**Comment by farhangnaderi** [comment]
@ryanjAA maybe able to test this as well?

**Comment by MaEtUgR** [comment]
I'm checking 🏃
For reference these are the minimal, hacky changes I did last time to build it:
https://github.com/facontidavide/PlotJuggler/compare/main...PX4:PlotJuggler:maetugr/initial-macm1

**Comment by MaEtUgR** [comment]
> I'm on apple silicon.

@mrpollo We're too, that's the main reason I'm using an Apple device at all.

> My issue still needs to be solved.

I have a feeling this is your toolchain/dependency setup.

> is not able to compile a simple test program.

Sounds pretty basic like the compiler not being available. Could it have to do with missing Apple [Xcode](https://apps.apple.com/us/app/xcode/id497799835) developer tools? I did not manually install it, was part of the brew installation for me and came in automatically. I followed https://github.com/MaEtUgR/MaEtUgR/blob/master/scripts/mac/brew.sh and already had the PX4 toolchain working before attempting PlotJuggler.

**Comment by MaEtUgR** [comment]
For me the build mainly fails with the `moc_datastream_zmq` failing compilation because the include libraries are somehow wrong. Haven't figured out where yet, these seem to be autogenerated in some unsupported way. I had `brew install zeromq` already installed and the include folder in cmake seems to be correct so the dependencies are just not correctly represented for the build step.
```
[ 86%] Building CXX object plotjuggler_plugins/DataStreamZMQ/CMakeFiles/DataStreamZMQ.dir/DataStreamZMQ_autogen/mocs_compilation.cpp.o
In file included from /Users/maetugr/PlotJugglerTest/build/plotjuggler_plugins/DataStreamZMQ/DataStreamZMQ_autogen/mocs_compilation.cpp:2:
In file included from /Users/maetugr/PlotJugglerTest/build/plotjuggler_plugins/DataStreamZMQ/DataStreamZMQ_autogen/EWIEGA46WW/moc_datastream_zmq.cpp:10:
In file included from /Users/maetugr/PlotJugglerTest/build/plotjuggler_plugins/DataStreamZMQ/DataStreamZMQ_autogen/EWIEGA46WW/../../../../../plotjuggler_plugins/DataStreamZMQ/datastream_zmq.h:9:
/Users/maetugr/PlotJugglerTest/plotjuggler_plugins/DataStreamZMQ/zmq.hpp:36:10: fatal error: 'zmq.h' file not found
#include <zmq.h>
         ^~~~~~~
1 error generated.
make[2]: *** [plotjuggler_plugins/DataStreamZMQ/CMakeFiles/DataStreamZMQ.dir/DataStreamZMQ_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [plotjuggler_plugins/DataStreamZMQ/CMakeFiles/DataStreamZMQ.dir/all] Error 2
make: *** [all] Error 2
```
My hacky solution was to just remove all ZMQ support because I don't use it but that's not something contributable and the fix from @farhangnaderi in this pr also doesn't work for me.
https://github.com/PX4/PlotJuggler/commit/591cb1d42e1e0183b9f6fc2b8c80ef7bbf134a88#diff-285967ff03f5fb94705efb5bebd763944b7591d7b23062885f4a4823ed10d1bfR12-R33

**Comment by MaEtUgR** [comment]
ok my initial hacks branch actually requires a patch to protobuf which is not workable at all. Here's the new one I just tested:
https://github.com/facontidavide/PlotJuggler/compare/main...PX4:PlotJuggler:maetugr/macm1-new
It's based on PlotJuggler upstream main, builds fine on 14.6.1 with brew all upgraded. Now we can solve things properly. I think @farhangnaderi already did some things correctly in this pr but the ZMQ fix doesn't work for me...

**Comment by farhangnaderi** [comment]
> ok my initial hacks branch actually requires a patch to protobuf which is not workable at all. Here's the new one I just tested: [facontidavide/PlotJuggler@main...PX4:PlotJuggler:maetugr/macm1-new](https://github.com/facontidavide/PlotJuggler/compare/main...PX4:PlotJuggler:maetugr/macm1-new) It's based on PlotJuggler upstream main, builds fine on 14.6.1 with brew all upgraded. Now we can solve things properly. I think @farhangnaderi already did some things correctly in this pr but the ZMQ fix doesn't work for me...

Thanks @MaEtUgR , 
Your solution leads to another protobuf error (am on SDK 15.0 now):

```
/Users/farhang/plotjuggler_ws/src/PlotJuggler/plotjuggler_plugins/ParserProtobuf/protobuf_factory.cpp:65:22: error: variable type 'FileErrorCollector' is an abstract class
   65 |   FileErrorCollector error_collector;
      |                      ^
/opt/homebrew/include/google/protobuf/compiler/importer.h:183:16: note: unimplemented pure virtual method 'RecordError' in 'FileErrorCollector'
  183 |   virtual void RecordError(absl::string_view filename, int line, int column,
      |                ^
1 warning and 1 error generated.
gmake[2]: *** [plotjuggler_plugins/ParserProtobuf/CMakeFiles/ProtobufParser.dir/build.make:129: plotjuggler_plugins/ParserProtobuf/CMakeFiles/ProtobufParser.dir/protobuf_factory.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2791: plotjuggler_plugins/ParserProtobuf/CMakeFiles/ProtobufParser.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```
I corrected them on this pull but your solution passed the classic zmq.h error.

File: COMPILE.md [hunk 2]
```diff
@@ -118,7 +120,7 @@ export LDFLAGS="$QT_HOME/lib"
...
```
Comment (dagar) [inline COMPILE.md]: Keep it clean so we can contribute upstream?

```suggestion
git clone https://github.com/facontidavide/PlotJuggler.git ~/plotjuggler_ws/src/PlotJuggler
```

File: .github/workflows/macos.yaml [hunk 3]
```diff
@@ -16,23 +16,35 @@ jobs:
       - name: Sync repository
         uses: actions/checkout@v2
 
+      - name: Update PATH
+        run: echo "PATH=$PATH:/opt/homebrew/bin:/opt/homebrew/sbin" >> $GITHUB_ENV
```
Comment (mrpollo) [inline .github/workflows/macos.yaml]: You no longer need this step

File: .github/workflows/macos.yaml [hunk 4]
```diff
@@ -16,23 +16,35 @@ jobs:
...
+        run: |
+          source $GITHUB_ENV
+          brew update
+          brew install mosquitto zeromq
+        shell: bash
+
       - name: Cache Qt
         id: cache-qt
-        uses: actions/cache@v1  # not v2!
+        uses: actions/cache@v4  # updated to v4
```
Comment (mrpollo) [inline .github/workflows/macos.yaml]: Remove comment

File: .github/workflows/macos.yaml [hunk 5]
```diff
@@ -16,23 +16,35 @@ jobs:
...
         with:
           path: '${{ github.workspace }}/qt_installation/'
           key: ${{ runner.os }}-QtCache
 
       - name: Install Qt
-        uses: jurplel/install-qt-action@v2.13.0
+        uses: jurplel/install-qt-action@v4.1.0  # updated to v4.1.0
```
Comment (mrpollo) [inline .github/workflows/macos.yaml]: Comments are not needed

File: .github/workflows/macos.yaml [hunk 6]
```diff
@@ -16,23 +16,35 @@ jobs:
...
         with:
           version: '5.15.2'
           host: 'mac'
           dir: '${{ github.workspace }}/qt_installation/'
           cached: ${{ steps.cache-qt.outputs.cache-hit }}
+          aqtversion: '==3.1.18'  # updated to 3.1.18
```
Comment (mrpollo) [inline .github/workflows/macos.yaml]: Again comments

**Review by mrpollo — CHANGES_REQUESTED** [review]

File: .github/workflows/macos.yaml [hunk 7]
```diff
@@ -5,34 +5,72 @@ on: [push, pull_request]
...
 
   macos-build:
-    runs-on: ${{ matrix.macos-version }}
+    runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
       matrix:
-        macos-version:
-          - 'macos-latest'
+        os:
```
Comment (mrpollo) [inline .github/workflows/macos.yaml:17]:
```suggestion
        os:
          - {arch: clang_64, os: macos-13}
          - {arch: arm64, os: macos-latest}
```

Comment (mrpollo) [reply .github/workflows/macos.yaml:17]: This way you don't have to iterate twice on your matrix. 

{matrix.os.arch | matrix.os.os}

File: .github/workflows/macos.yaml [hunk 8]
```diff
@@ -5,34 +5,48 @@ on: [push, pull_request]
...
 
       - name: Build Plotjuggler
         shell: pwsh
-        run: >
-          cmake -B build -DCMAKE_INSTALL_PREFIX=install PlotJuggler;
+        run: |
+          cmake -B build -DCMAKE_INSTALL_PREFIX=install PlotJuggler
           cmake --build build --target install
+
+      - name: Setup tmate session
```
Comment (mrpollo) [inline .github/workflows/macos.yaml]:
```suggestion
      - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3

```

File: .github/workflows/macos.yaml [hunk 9]
```diff
@@ -3,36 +3,42 @@ name: macos
...
-      - name: Build Plotjuggler
-        shell: pwsh
-        run: >
-          cmake -B build -DCMAKE_INSTALL_PREFIX=install PlotJuggler;
+      - name: Install dependencies
+        run: |
+          brew update
+          brew install mosquitto zeromq qt@5
+
+      - name: Set environment variables
```
Comment (mrpollo) [inline .github/workflows/macos.yaml]: update the name to match whats going on, maybe rename to "Build PlotJuggler"

File: .github/workflows/macos.yaml [hunk 10]
```diff
@@ -3,36 +3,42 @@ name: macos
...
-          cached: ${{ steps.cache-qt.outputs.cache-hit }}
-
-      - name: Build Plotjuggler
-        shell: pwsh
-        run: >
-          cmake -B build -DCMAKE_INSTALL_PREFIX=install PlotJuggler;
+      - name: Install dependencies
+        run: |
+          brew update
+          brew install mosquitto zeromq qt@5
```
Comment (mrpollo) [inline .github/workflows/macos.yaml:30]: Any reason to not use the same instructions in COMPILE.md to install and link qt5?

File: .github/workflows/macos.yaml [hunk 11]
```diff
@@ -3,36 +3,42 @@ name: macos
...
-      - name: Cache Qt
-        id: cache-qt
-        uses: actions/cache@v1  # not v2!
-        with:
-          path: '${{ github.workspace }}/qt_installation/'
-          key: ${{ runner.os }}-QtCache
+      - name: Clean Homebrew locks and cache
+        run: |
+          rm -rf /usr/local/var/homebrew/locks
+          brew cleanup -s
```
Comment (mrpollo) [inline .github/workflows/macos.yaml:28]: you can likely append this to the next step so you have everything homebrew related in a single step

File: .github/workflows/macos.yaml [hunk 12]
```diff
@@ -3,36 +3,42 @@ name: macos
...
   macos-build:
-    runs-on: ${{ matrix.macos-version }}
+    runs-on: ${{ matrix.os.os }}
     strategy:
       fail-fast: false
       matrix:
-        macos-version:
-          - 'macos-latest'
+        os:
+          - {arch: clang_64, os: macos-13}
```
Comment (mrpollo) [inline .github/workflows/macos.yaml]: It looks like you are no longer using the arch variable. Would you like to return to a simple list of macOS versions?

File: .github/workflows/macos.yaml [hunk 13]
```diff
@@ -3,36 +3,42 @@ name: macos
 on: [push, pull_request]
```
Comment (mrpollo) [inline .github/workflows/macos.yaml]: Since we are already updating this file, it is best to update the push trigger to only work on the main branch. This will help decrease the GitHub action runs on each PR.

```suggestion
on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'
```

**Review by mrpollo — APPROVED** [review]
